version: '3.8'

services:
  server:
    depends_on: 
      - database
    build:
      context: .
    container_name: gpa-calculator-server
    hostname: gpa-calculator-server
    networks:
      - mynet
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure
  database:
    image: postgres:alpine
    container_name: gpa-calculator-database
    hostname: db
    networks:
      - mynet
    environment:
      - POSTGRES_USER:${DB_USER}
      - POSTGRES_DB:${DB_NAME}
      - POSTGRES_PASSWORD:${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate:latest
    networks:
      - mynet
    volumes:
      - ./migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgres://admin:password@database:5432/gpa_calculator?sslmode=disable",
      ]
    command: ["up"]
    depends_on:
      - database 

volumes:
  data:

networks:
  mynet:
    driver: bridge